from typing import Any, TypeVar

from .test_column import TestColumn
from .test_table import TestTable

T = TypeVar("T")


class Data:
    """One row to insert: a TestTable plus its column values. A column value
    is either an immediate literal or another Data (resolved to that row's
    generated id at insert time, for foreign keys). A referenced Data must
    already be registered on the builder (template methods always create and
    register a parent before building a child that references it), so the
    builder never needs to insert it out of order.
    """

    def __init__(self, table: TestTable, index: int = 0) -> None:
        self._table = table
        self._index = index
        self._columns: dict[str, Any] = {}
        self._generated_id: int | None = None
        self._added = False

    def set_column(self, column: TestColumn | str, value: Any) -> "Data":
        """Sets a column value, by raw SQL column name or TestColumn."""
        sql_name = column.sql_name if isinstance(column, TestColumn) else column
        self._columns[sql_name] = value
        return self

    def get_column(self, column: TestColumn | str) -> Any:
        """Reads back a column value set via set_column, for assertions."""
        sql_name = column.sql_name if isinstance(column, TestColumn) else column
        return self._columns.get(sql_name)

    @property
    def table(self) -> TestTable:
        """The table this row belongs to."""
        return self._table

    @property
    def index(self) -> int:
        """The table-scoped index this Data was created with, see
        TestDataBuilder.new_data."""
        return self._index

    @property
    def columns(self) -> dict[str, Any]:
        """Every column value set so far, keyed by SQL column name."""
        return self._columns

    @property
    def generated_id(self) -> int | None:
        """The id generated by the database for this row, once
        TestDataBuilder.create() has inserted it."""
        return self._generated_id

    def _set_generated_id(self, generated_id: int) -> None:
        self._generated_id = generated_id

    @property
    def is_added(self) -> bool:
        """Whether TestDataBuilder.create() has already inserted this row."""
        return self._added

    def _mark_added(self) -> None:
        self._added = True
